# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       mlspp

# >> macros
# << macros

Summary:    Template Project
Version:    0.1.0
Release:    0
Group:      Applications
License:    ASL 2.0
URL:        https://codeberg.org/nephros/template
Source0:    %{name}-%{version}.tar.gz
Source100:  mlspp.yaml
Source101:  mlspp-rpmlintrc

%description


%if "%{?vendor}" == "chum"
Title: Template Application
DeveloperName: Peter G.
DeveloperLogin: nephros
PackagedBy: nephros
Categories:
 - Library
Custom:
  Repo: https://github.com/cisco/mlspp
PackageIcon: %{url}/master/icons/%{name}.svg
Screenshots:
 - %{url}/raw/metadata/screenshots/screenshot1.png
 - %{url}/raw/metadata/screenshots/screenshot2.png
 - %{url}/raw/metadata/screenshots/screenshot3.png
Links:
  Homepage: %{url}
  Help: %{url}/discussions
  Bugtracker: %{url}/issues
  Donation: https://openrepos.net/donate
%endif


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake . 
make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%license LICENSE
%dir %{_datadir}/%{name}
# >> files
# << files
